// Dev tool: regenerates src/shapes/iconBounds.generated.ts by measuring each
// shape's drawn silhouette. Requires the Vite dev server running (npm run dev).
// Usage: node measure-bounds.mjs
import { chromium } from 'playwright'
import { writeFileSync } from 'node:fs'
const BASE = 'http://localhost:5173'
const IDS = `arch-core:api-gateway arch-core:boundary arch-core:cache arch-core:cdn arch-core:client arch-core:database arch-core:dns arch-core:external arch-core:function arch-core:iot arch-core:laptop arch-core:load-balancer arch-core:mobile arch-core:queue arch-core:server arch-core:service arch-core:storage arch-core:user basic:diamond basic:ellipse basic:rectangle basic:text cloud:az cloud:block-storage cloud:cloud cloud:cluster cloud:container cloud:data-warehouse cloud:event-bus cloud:firewall cloud:idp cloud:internet cloud:monitoring cloud:object-storage cloud:region cloud:serverless cloud:vault cloud:vm cloud:vpn flow:action flow:connector flow:db flow:display flow:document flow:form flow:io flow:manual-input flow:manual-op flow:multi-document flow:off-page flow:process flow:screen flow:stored-data flow:subprocess flow:terminator k8s:configmap k8s:cronjob k8s:daemonset k8s:deployment k8s:ingress k8s:job k8s:namespace k8s:pod k8s:pv k8s:secret k8s:service k8s:statefulset uml:activation uml:actor uml:boundary uml:class uml:component uml:interface uml:lifeline uml:lollipop uml:note uml:object uml:package uml:use-case`.split(/\s+/)

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1000, height: 800 } })
await page.goto(BASE, { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.clear()); await page.reload({ waitUntil: 'networkidle' })

const bounds = await page.evaluate(async (ids) => {
  const store = window.__graffel.useDiagramStore
  async function measure(svgEl) {
    const clone = svgEl.cloneNode(true)
    clone.setAttribute('width', '100'); clone.setAttribute('height', '100')
    clone.setAttribute('preserveAspectRatio', 'none') // viewBox 0-100 maps 1:1 to px
    const xml = new XMLSerializer().serializeToString(clone)
    const url = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(xml)
    const img = new Image()
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = url })
    const c = document.createElement('canvas'); c.width = 100; c.height = 100
    const ctx = c.getContext('2d'); ctx.clearRect(0, 0, 100, 100); ctx.drawImage(img, 0, 0, 100, 100)
    const d = ctx.getImageData(0, 0, 100, 100).data
    let minX = 100, minY = 100, maxX = 0, maxY = 0, any = false
    for (let y = 0; y < 100; y++) for (let x = 0; x < 100; x++) {
      if (d[(y * 100 + x) * 4 + 3] > 10) { any = true; if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y }
    }
    if (!any) return null
    return { x: minX, y: minY, w: maxX - minX, h: maxY - minY }
  }
  const out = {}
  for (const id of ids) {
    store.setState({ nodes: [], edges: [], selectedNodeIds: [], selectedEdgeIds: [] })
    const nid = store.getState().addNode(id, { x: 50, y: 50 })
    await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))
    const svg = document.querySelector(`.react-flow__node [data-shape-id="${id}"] .graffel-shape-body svg`)
    out[id] = svg ? await measure(svg) : null
  }
  return out
}, IDS)

await browser.close()

const ids = Object.keys(bounds).filter((k) => bounds[k])
let out = `// AUTO-GENERATED by measure-bounds.mjs — tight silhouette bbox per shape in
// 0–100 viewBox coords, measured from the rendered icon pixels. Feeds
// resolveAnchors so connection handles sit on the drawn edge. Do not edit by
// hand; regenerate with: node measure-bounds.mjs (Vite dev server must be up).

export const ICON_BOUNDS: Record<string, { x: number; y: number; w: number; h: number }> = {
`
for (const id of ids) {
  const v = bounds[id]
  out += `  '${id}': { x: ${v.x}, y: ${v.y}, w: ${v.w}, h: ${v.h} },\n`
}
out += '}\n'
writeFileSync('src/shapes/iconBounds.generated.ts', out)
console.log(`wrote ${ids.length} entries to src/shapes/iconBounds.generated.ts`)
